modules/06_projekt_final/blog_project/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :articles do
    resources :comments
  end
  
end

modules/06_projekt_final/blog_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

modules/06_projekt_final/blog_project/app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true, length: { minimum: 3 }
  validates :text, presence: true

  has_many :comments, dependent: :destroy


end

modules/06_projekt_final/blog_project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, :body, presence: true
end

modules/06_projekt_final/blog_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

modules/06_projekt_final/blog_project/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
     @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end


  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

modules/06_projekt_final/blog_project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

modules/06_projekt_final/blog_project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

modules/06_projekt_final/blog_project/app/helpers/application_helper.rb
module ApplicationHelper
end

modules/06_projekt_final/blog_project/app/helpers/articles_helper.rb
module ArticlesHelper
end

modules/06_projekt_final/blog_project/app/helpers/comments_helper.rb
module CommentsHelper
end

modules/06_projekt_final/blog_project/app/helpers/welcome_helper.rb
module WelcomeHelper
end

modules/06_projekt_final/blog_project/app/views/articles/edit.html.erb
<h1>Artikel bearbeiten</h1>

<%= form_with(model: @article, local: true) do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Zurück', articles_path %>

modules/06_projekt_final/blog_project/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'Neuer Artikel', new_article_path %>

<table>
  <tr>
    <th>Titel</th>
    <th>Inhalt</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Anzeigen', article_path(article) %></td>
      <td><%= link_to 'Bearbeiten', edit_article_path(article) %></td>
      <td><%= link_to 'Loeschen', article_path(article),
              method: :delete,
              data: { confirm: 'Sind Sie sicher?' } %></td>
    </tr>
  <% end %>
</table>

modules/06_projekt_final/blog_project/app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>

  <% if @article.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@article.errors.count, "error") %> prohibited
         this article from being saved:
       </h2>
       <ul>
         <% @article.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Zurück', articles_path %>

modules/06_projekt_final/blog_project/app/views/articles/show.html.erb
<p>
  <strong>Titel:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Inhalt:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

modules/06_projekt_final/blog_project/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Loesche Kommentar', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Sind Sie sicher?' } %>
</p>

modules/06_projekt_final/blog_project/app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

modules/06_projekt_final/blog_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

modules/06_projekt_final/blog_project/app/views/welcome/index.html.erb
<h1>Hallo, Rails!</h1>
<%= link_to 'Mein Blog', controller: 'articles' %>